"""initial_migration

Revision ID: 763db5773683
Revises: 
Create Date: 2026-03-14 15:44:31.566760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763db5773683'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Сначала создаем пользователей
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(length=30), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(length=255), nullable=False),
                    sa.Column('online_status', sa.Boolean(), nullable=False),
                    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # 2. Создаем чаты (БЕЗ ссылки на messages пока что)
    op.create_table('chats',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('type', sa.Enum('private', 'group', name='chat_type'), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('description', sa.String(length=500), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.Column('creator_id', sa.Integer(), nullable=True),
                    sa.Column('last_message_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_chats_creator_id'), 'chats', ['creator_id'], unique=False)
    op.create_index(op.f('ix_chats_type'), 'chats', ['type'], unique=False)

    # 3. Теперь создаем сообщения (теперь ссылка на chats.id сработает)
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.Column('status', sa.Enum('sent', 'delivered', 'read', name='message_status'), nullable=False),
                    sa.Column('read_by', sa.String(length=500), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)

    # 4. Участники чата
    op.create_table('chat_participants',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=False),
                    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'chat_id')
                    )

    # 5. ФИНАЛЬНЫЙ ШТРИХ: Связываем чат с последним сообщением (теперь обе таблицы созданы)
    op.create_foreign_key('fk_chats_last_message', 'chats', 'messages', ['last_message_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_chats_last_message_id'), 'chats', ['last_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_participants')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chats_type'), table_name='chats')
    op.drop_index(op.f('ix_chats_last_message_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_creator_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
